<?php
declare(strict_types=1);

namespace Sotr;

/**
 * Turns the stored documents back into the exact data files the website already reads
 * (window.SITE_SHOP, window.SITE_RUNS, …). English goes to its usual file; the Arabic
 * written beside each item is gathered into data/ar.js, matched by id as before.
 */
final class Generator
{
    public const FILES = ['config.js', 'products.js', 'runs.js', 'packages.js', 'testimonials.js', 'ar.js'];

    /** @param array<string, array> $docs  area => document @return array<string, string> filename => contents */
    public static function files(array $docs): array
    {
        $shop = $docs['shop'] ?? ['categories' => []];
        $runs = $docs['runs'] ?? ['events' => []];
        $offer = $docs['offer'] ?? [];
        $extras = $docs['extras'] ?? [];

        return [
            'config.js'       => self::js('SITE', $docs['settings'] ?? []),
            'products.js'     => self::js('SITE_SHOP', self::english($shop)),
            'runs.js'         => self::js('SITE_RUNS', self::english($runs)),
            'packages.js'     => self::js('SITE_OFFER', self::english($offer)),
            'testimonials.js' => self::js('SITE_TESTIMONIALS', self::english($docs['testimonials']['items'] ?? [])),
            'ar.js'           => self::js('SITE_AR', self::arabic($shop, $runs, $offer, $extras)),
        ];
    }

    /** The document with every "ar" key removed. */
    public static function english(mixed $node): mixed
    {
        if (!is_array($node)) {
            return $node;
        }
        $out = [];
        foreach ($node as $k => $v) {
            if ($k === 'ar' && !array_is_list($node)) {
                continue;
            }
            $out[$k] = self::english($v);
        }
        return $out;
    }

    private static function arabic(array $shop, array $runs, array $offer, array $extras): array
    {
        $byId = static function (array $list): array {
            $map = [];
            foreach ($list as $x) {
                if (!empty($x['ar']) && isset($x['id'])) {
                    $map[$x['id']] = $x['ar'];
                }
            }
            return $map;
        };

        $items = [];
        foreach ($shop['categories'] ?? [] as $c) {
            $items += $byId($c['items'] ?? []);
        }

        $ar = [
            'services'  => $byId($offer['services'] ?? []),
            'packages'  => $byId($offer['packages'] ?? []),
            'challenge' => $offer['challenge']['ar'] ?? null,
            'fit'       => $offer['ar']['fit'] ?? null,
            'recurring' => $runs['recurring']['ar'] ?? null,
            'events'    => $byId($runs['events'] ?? []),
            'shop'      => ['categories' => $byId($shop['categories'] ?? []), 'items' => $items],
            'governorates' => $shop['ar']['governorates'] ?? null,
        ];
        foreach ($extras['ar'] ?? [] as $k => $v) {
            $ar[$k] = $v;
        }
        return array_filter($ar, static fn ($v) => $v !== null);
    }

    private static function js(string $global, mixed $data): string
    {
        $json = json_encode(
            self::objects($data),
            JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR
        );
        return "/* Generated by the SheOnTheRun admin panel. Edit it at /admin — changes made\n"
            . "   to this file by hand are replaced the next time someone presses Publish. */\n\n"
            . "window.$global = $json;\n";
    }

    /** Empty maps must stay objects ({}), not become lists ([]), in the generated JavaScript. */
    private static function objects(mixed $node): mixed
    {
        if (!is_array($node)) {
            return $node;
        }
        if ($node === []) {
            return $node;
        }
        $out = [];
        foreach ($node as $k => $v) {
            $out[$k] = self::objects($v);
        }
        if (!array_is_list($node)) {
            return (object) $out;
        }
        return $out;
    }
}
