/* Proves the admin panel can take over the site's files without changing the website:
   seed → validator → generator must give back exactly what today's hand-made files say.
     node --test server/tests/roundtrip.test.mjs */
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { phpCommand } from "./php.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
let out;

function load(dir, files) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  for (const f of files) vm.runInContext(readFileSync(join(dir, f), "utf8"), sandbox, { filename: f });
  return JSON.parse(JSON.stringify(sandbox.window));
}
const read = (p) => readFileSync(p, "utf8").split("\r\n").join("\n");
const squash = (s) => s.replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();

before(() => {
  out = mkdtempSync(join(tmpdir(), "sotr-gen-"));
  const [php, args] = phpCommand();
  const r = spawnSync(php, [...args, join(root, "server", "bin", "generate.php"), out], { encoding: "utf8" });
  assert.equal(r.status, 0, `generator failed:\n${r.stdout}\n${r.stderr}`);
});
after(() => rmSync(out, { recursive: true, force: true }));

test("every generated data file has exactly today's values", () => {
  const files = ["config.js", "products.js", "runs.js", "packages.js", "testimonials.js", "ar.js", "posts.js", "images.js", "gallery.js"];
  const before = load(join(root, "data"), files);
  const after = load(out, files);
  for (const g of ["SITE", "SITE_SHOP", "SITE_RUNS", "SITE_OFFER", "SITE_TESTIMONIALS", "SITE_AR", "SITE_POSTS", "SITE_IMAGES", "SITE_GALLERY"]) {
    assert.deepStrictEqual(after[g], before[g], `${g} differs`);
  }
  assert.match(readFileSync(join(out, "images.js"), "utf8"), /Generated by the SheOnTheRun admin panel/);
});

test("feed.xml and sitemap.xml match what the CI build writes today", () => {
  assert.equal(read(join(out, "feed.xml")).trim(), read(join(root, "feed.xml")).trim());
  assert.equal(read(join(out, "sitemap.xml")).trim(), read(join(root, "sitemap.xml")).trim());
});

for (const slug of ["a-month-in-shanghai", "fuelling-your-first-10k"]) {
  test(`the generated page for "${slug}" keeps every word and the same structure`, () => {
    const was = read(join(root, "journal", slug + ".html"));
    const now = read(join(out, "journal", slug + ".html"));
    const part = (html, re) => (re.exec(html) || [])[1];
    assert.ok(existsSync(join(out, "journal", slug + ".html")));
    assert.equal(squash(part(now, /<div class="prose mt-l">([\s\S]*?)<div class="discovery/)), squash(part(was, /<div class="prose mt-l">([\s\S]*?)<div class="discovery/)), "article text");
    for (const re of [/<h1[^>]*>([^<]*)<\/h1>/, /<p class="measured mt-m">([^<]*)<\/p>/, /<p class="lede[^>]*>([^<]*)<\/p>/, /<link rel="canonical" href="([^"]*)"/, /og:image" content="([^"]*)"/, /<title>([^<]*)<\/title>/, /<meta name="description" content="([^"]*)"/, /data-img="([^"]*)"/]) {
      assert.equal(part(now, re), part(was, re), String(re));
    }
    // the same lists, quotes and bold text survive
    for (const tag of ["<h2>", "<blockquote>", "<ul>", "<li>", "<strong>"]) {
      assert.equal(now.split(tag).length, was.split(tag).length, tag + " count");
    }
  });
}
