/* Proves the admin panel can take over the data files without changing the website:
   seed → validator → generator must give back exactly the values in today's data/*.js.
     node --test server/tests/roundtrip.test.mjs */
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { phpCommand } from "./php.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

function load(dir, files) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  for (const f of files) vm.runInContext(readFileSync(join(dir, f), "utf8"), sandbox, { filename: f });
  return JSON.parse(JSON.stringify(sandbox.window));
}

test("publishing the imported content reproduces today's data files exactly", () => {
  const out = mkdtempSync(join(tmpdir(), "sotr-gen-"));
  try {
    const [php, args] = phpCommand();
    const r = spawnSync(php, [...args, join(root, "server", "bin", "generate.php"), out], { encoding: "utf8" });
    assert.equal(r.status, 0, `generator failed:\n${r.stdout}\n${r.stderr}`);

    const files = ["config.js", "products.js", "runs.js", "packages.js", "testimonials.js", "ar.js"];
    const before = load(join(root, "data"), files);
    const after = load(out, files);
    for (const g of ["SITE", "SITE_SHOP", "SITE_RUNS", "SITE_OFFER", "SITE_TESTIMONIALS", "SITE_AR"]) {
      assert.deepStrictEqual(after[g], before[g], `${g} differs`);
    }
    assert.match(readFileSync(join(out, "products.js"), "utf8"), /Generated by the SheOnTheRun admin panel/);
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
});
